# Generated by Django 5.1.3 on 2025-04-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_em_estoque', models.IntegerField()),
                ('quantidade_minima', models.IntegerField(default=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
                ('nome', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.categoriamanutencao')),
            ],
        ),
        migrations.CreateModel(
            name='Reabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.PositiveIntegerField()),
                ('data_reabastecimento', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reabastecimentos', to='estoque.estoque')),
            ],
        ),
    ]
