# Generated by Django 5.1.3 on 2025-01-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0011_alter_servicocategoriaquantidade_valor_mao_de_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_em_estoque', models.IntegerField()),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.categoriamanutencao')),
            ],
        ),
    ]
