# Generated by Django 5.1.3 on 2025-01-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
