# Generated by Django 5.1.3 on 2025-01-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_estoque_atualizado_em'),
        ('servicos', '0011_alter_servicocategoriaquantidade_valor_mao_de_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.categoriamanutencao'),
        ),
    ]
