# Generated by Django 5.1.3 on 2025-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_listacompras_estoque_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacompras',
            name='data_da_compra',
            field=models.DateTimeField(),
        ),
    ]
