# Generated by Django 5.1.3 on 2025-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_listacompras_data_da_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacompras',
            name='data_da_compra',
            field=models.DateField(),
        ),
    ]
