# Generated by Django 5.1.3 on 2025-04-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_listacompras_data_da_compra'),
        ('servicos', '0011_alter_servicocategoriaquantidade_valor_mao_de_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='lista',
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdicionarItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.IntegerField()),
                ('data_adicionado', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.categoriamanutencao')),
            ],
        ),
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
