# Generated by Django 5.1.3 on 2025-04-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_estoque_lista_estoque_quantidade_minima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.CreateModel(
            name='Reabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_adicionada', models.PositiveIntegerField()),
                ('data_reabastecimento', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reabastecimentos', to='estoque.estoque')),
            ],
        ),
        migrations.DeleteModel(
            name='AdicionarItens',
        ),
    ]
