# Generated by Django 5.1.3 on 2025-04-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_estoque_quantidade_minima_reabastecimento_and_more'),
        ('servicos', '0011_alter_servicocategoriaquantidade_valor_mao_de_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.categoriamanutencao'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='reabastecimento',
            name='data_reabastecimento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
