# Generated by Django 5.1.3 on 2025-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_estoque_nome_alter_estoque_quantidade_minima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_minima',
            field=models.IntegerField(default=10),
        ),
    ]
