from django.db.models import TextChoices

class ChoicesCategoriaManutencao(TextChoices):
    TROCAR_OLEO = 'TROCA DE OLEO', 'TROCA DE OLEO' # OK
    TROCAR_AMORTECEDOR = 'TROCA DE AMORTECEDOR', 'TROCA DE AMORTECEDOR' # OK
    TROCAR_CABO_FREIO = 'TROCA DE CABO DE FREIO', 'TROCA DE CABO DE FREIO' # OK
    ALINHAMENTO_BALANCEAMENTO = 'ALINHAMENTO E BALANCEAMENTO', 'ALINHAMENTO E BALANCEAMENTO' # OK
    TROCAR_PNEUS = 'TROCA DE PNEU (D)', 'TROCA DE PNEU (D)' # OK
    TROCAR_FILTRO_AR = 'TROCA DE FILTRO DE AR', 'TROCA DE FILTRO DE AR' # OK
    TROCAR_BATERIA = 'TROCA DE BATERIA', 'TROCA DE BATERIA' # OK
    TROCAR_VELAS_IGNICAO = 'TROCA DE VELAS DE IGNIÇÃO', 'TROCA DE VELAS DE IGNIÇÃO' # OK
    TROCAR_CORRENTE = 'TROCA DE CORRENTE', 'TROCA DE CORRENTE'
    TROCAR_DISCO_FREIO = 'TROCA DE DISCO DE FREIO', 'TROCA DE DISCO DE FREIO'
    TROCAR_LAMPADAS = 'TROCA DE LÂMPADAS', 'TROCA DE LÂMPADAS'
    TROCAR_EMBREAGEM = 'TROCA DE EMBREAGEM', 'TROCA DE EMBREAGEM'
    TROCAR_RADIADOR = 'TROCA DE RADIADOR', 'TROCA DE RADIADOR'
    TROCAR_SUSPENSAO = 'TROCA DE SUSPENSÃO', 'TROCA DE SUSPENSÃO'

