# Generated by Django 5.1.3 on 2025-04-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoCategoriaQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.categoriamanutencao')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mecanico_resp', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('status', models.CharField(default='Em Orçamento', max_length=25)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('notifica_cliente', models.BooleanField(default=True, max_length=5)),
                ('protocolo', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.carro')),
                ('categoria_manutencao', models.ManyToManyField(through='servicos.ServicoCategoriaQuantidade', to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='servicocategoriaquantidade',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos'),
        ),
    ]
