# Generated by Django 5.1.3 on 2024-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='mecanico_resp',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
