# Generated by Django 5.1.3 on 2024-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servicos_mecanico_resp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='servicos',
            name='status',
            field=models.CharField(default='Em Orçamento', max_length=25),
        ),
    ]
