# Generated by Django 5.1.3 on 2024-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_remove_servicos_finalizado_servicos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='notifica_cliente',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
