# Generated by Django 5.1.3 on 2024-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servicos_notifica_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='notifica_cliente',
            field=models.BooleanField(default=True, max_length=5),
        ),
    ]
