# Generated by Django 5.1.3 on 2024-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_servicos_notifica_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
