# Generated by Django 5.1.3 on 2024-12-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_categoriamanutencao_valor_mao_de_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriamanutencao',
            name='valor_mao_de_obra',
        ),
        migrations.AddField(
            model_name='servicocategoriaquantidade',
            name='valor_mao_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
