# Generated by Django 5.1.3 on 2024-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_remove_categoriamanutencao_valor_mao_de_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocategoriaquantidade',
            name='valor_mao_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
