# Generated by Django 5.1.3 on 2024-12-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_alter_servicocategoriaquantidade_valor_mao_de_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocategoriaquantidade',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
